In [1]:
import torch

c:\Users\levy\.conda\envs\deep\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
b  = torch.tensor([0.])
X = torch.tensor(
    [
        [1.2, 2.2],
        [4.4, 5.5]
    ]
)

w = torch.tensor(
    [3.3, 4.3]
)


In [3]:
torch.matmul(X, w) + b

tensor([13.4200, 38.1700])

In [4]:
X = torch.rand(100, 10)
W = torch.rand(50, 10)

In [5]:
torch.matmul(X, W.T).shape

torch.Size([100, 50])

In [6]:
X = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6, 5], [7, 8, 9]])

# X[0][1] = 'a'



X.matmul(y)





tensor([[19, 22, 23],
        [43, 50, 51]])

# Differentiation

In [7]:
w_1 = torch.tensor([0.23], requires_grad=True)
b = torch.tensor([0.1], requires_grad=True)

x_1 = torch.tensor(([1.23]))
y = torch.tensor([1.])


In [9]:
u = x_1 * w_1
z = u+b
print(z)

tensor([0.3829], grad_fn=<AddBackward0>)


In [11]:
a = torch.sigmoid(z)


a

tensor([0.5946], grad_fn=<SigmoidBackward0>)

In [15]:
import torch.nn.functional as F
from torch.autograd import grad

l = F.binary_cross_entropy_with_logits(z, y)
l

tensor(0.5199, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [16]:
grad_L_w_1 = grad(l, w_1, retain_graph=True)
grad_L_b = grad(l, b, retain_graph=True)

In [17]:
grad_L_b

(tensor([-0.4054]),)

In [18]:
l.backward()

In [20]:
w_1.grad, b.grad

(tensor([-0.4987]), tensor([-0.4054]))

In [21]:
# linear layer

torch.manual_seed(123)

linear = torch.nn.Linear(in_features=2, out_features=1)

In [24]:
linear.bias

Parameter containing:
tensor([-0.3512], requires_grad=True)

In [25]:
x = torch.tensor([[1.2, 0.5]])

w = linear.weight.detach()
b = linear.bias.detach()
z = x.matmul(w.T) + b
print(z)

tensor([[-0.6855]])


In [26]:
linear(x)

tensor([[-0.6855]], grad_fn=<AddmmBackward0>)

In [27]:
x = torch.tensor([
    [1.2, 0.5],
    [0.7, 0.8],
    [0.1, 0.2]
])

print(x)

tensor([[1.2000, 0.5000],
        [0.7000, 0.8000],
        [0.1000, 0.2000]])


In [28]:
linear(x)

tensor([[-0.6855],
        [-0.5343],
        [-0.3753]], grad_fn=<AddmmBackward0>)